### ISSUE TITLE
Conflict with "FastBench" and "FastFurnace"

### ISSUE THREAD

**Issue by krisjenner** [DosMike/EquivalentMatterExchange#2]
Devices not forming due to FastBench and FastFurnace mods being installed - could you add a config option to devices.cfg to define which blocks can be used or find a way around this? this plugin is amazing!

**Comment by DosMike** [comment]
Thanks for you compliment.
I won't be able to work on things for the next 3 weeks. I'll take a look at it when I'm back

**Comment by Shadows-of-Fire** [comment]
(Author of FB/FF)

So this problem stems from what appears to be sponge not updating their block references when forge applies a registry override.  You could get around this by checking the name of the blocks instead of checking against the sponge BlockType object, but without direct interfacing to forge I can't think of too many other solutions.

**Comment by DosMike** [comment]
Looks like when FB/FF replaces the `BlockType`s in the `BlockTypes`-Catalog completely break.
I wrapped the type comparison now, and `BlockTypes.FURNACE.getId()` just dies.
```
java.lang.RuntimeException: Block 'Block{null}' (class 'net.minecraft.block.BlockFurnace') is not registered with the block registry! This is likely a bug in the corresponding mod.
        at net.minecraft.block.Block.getNameFromRegistry(Block.java:2820) ~[aow.class:?]
        at net.minecraft.block.Block.getId(Block.java:2806) ~[aow.class:?]
        at de.dosmike.sponge.equmatterex.util.ForgeHelper.isOfType(ForgeHelper.java:14) ~[ForgeHelper.class:?]
```

For now I just got rid of the Sponge Catalog and compare the raw ID with Strings.

I think the best solution would be to use Mixins to replace the Vanilla `BlockTypes` entries with the FB/FF overwrites, but I have no idea how Mixins work. 

Anyways... I got it to work on my test server and will push the update. Thanks again @Shadows-of-Fire

**Comment by Shadows-of-Fire** [comment]
You should be able to replace those values with reflection instead of mixins, as long as you do it after preinit
