### ISSUE TITLE
Console spam after update 0.3

### ISSUE THREAD

**Issue by krisjenner** [DosMike/EquivalentMatterExchange#3]
Hey, not really a severe issue but my console is being spammed with "comparing" after installing the 0.3 version

**Comment by DosMike** [comment]
Sorry about that, should be fixed

**Comment by krisjenner** [comment]
I think it ended up fixing itself, upon waking up this morning the console was fine!

**Comment by DosMike** [comment]
Unlikely, The console will just hide messages that spam too much and thus might be irrelevant (the log might still be spammed). I removed the message in 0.3.1
