### ISSUE TITLE
Furnace not recognised

### ISSUE THREAD

**Issue by krisjenner** [DosMike/EquivalentMatterExchange#4]
Hey! The chest and workbench with daylight sensor forms and works fine, although the furnace (collector) doesn't. I get this error in console upon removing my attempt

`[14:28:00] [Server thread/INFO] [equmatterex]: Removed invalid device Collector at -1588 65 2077`

This server has FastFurnace installed

**Comment by krisjenner** [comment]
Also I believe it may be spawning multiple [armor stands ](https://imgur.com/a/s4CsYLU)

**Comment by DosMike** [comment]
Sorry, missed the collector.
I can't replicate the armor stand thing tho, if this is an error that persists, please make a separate issue on that.
