### ISSUE TITLE
Exact copy from condenser

### ISSUE THREAD

**Issue by SykoUSS** [DosMike/EquivalentMatterExchange#5]
Unlike the transmutation table, the condenser creates an exact copy of the targeted item. This might not necessarily be an issue, but can be a problem in some cases(servers that may have crate keys or other things you may not want copied). It may be better for the condenser to copy base item type and not to clone the item.

**Comment by DosMike** [comment]
Config options for this are now available, as e.g. Fireworks might be alright keeping NBT
